class: 'bvae'
dense: 'true'
encoder:
    out_features: (512, 512)
latent_dim: 10
decoder:
    out_features: (512, 512)
beta: 1
optimizer:
    type: "Adam"
    lr: 0.0001
    weight_decay: 0
    metrics: ["roc_auc"]
