class: 'bvaeconv'
dense: 'true'
encoder:
    out_features: [16, 32, 32]
latent_dim: 2
causal_latents: 1
decoder:
    out_features: [32, 32, 1]
beta: 1
processing_mode: '2d'
optimizer:
    type: "Adam"
    lr: 0.0001
    weight_decay: 0

