# Config file
name: "LatentGranger"
n_gpu: 0
arch:
    LatentGranger:
        encoder:
            out_features: (1024, 512, 256, 128)
        latent_dim: 20
        decoder:
            out_features: (128, 256, 512, 1024)
        beta: 0.01
        lag: 4
    resume: ""
    initial_weights: ''
data:
    Toy:
        seed_idx: 0
        root: './databases/data/toy'
        input_size: (128,128)
        dense_input_size: 16384
        dimension: 1
        statistics_root: './databases/data/toy/data_py/statistics.npz'
        nsamples_train: 300
        nsamples_val: 300
        nsamples_test: 300
        batch_size: 1
        tpb: 300
    AfricaPrecip:
        seed_idx: 0
        input_size: (150, 150)
        dense_input_size: 11719 
        root: './databases/data/africa_precip/'
        years:  [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        nsamples_train: 200
        nsamples_val: 100
        nsamples_test: 100
        batch_size: 1
        tpb: 100
        root_ENSO: './databases/data/inino34_daily.dat'
        root_LC: './databases/data/africa_LC.tif'
    AfricaPrecipns:
        seed_idx: 0
        input_size: (150, 150)
        dense_input_size: 11719 
        root: './databases/data/africa_precip_ns/'
        years:  [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        nsamples_train: 200
        nsamples_val: 100
        nsamples_test: 100
        batch_size: 1
        tpb: 100
        root_ENSO: './databases/data/inino34_daily.dat'
        root_LC: './databases/data/africa_LC.tif'
    AfricaNDVI:
        seed_idx: 0
        input_size: (150, 150)
        dense_input_size: 11719 
        root: './databases/data/africa_ndvi/'
        template: 'ndvi_TMSTMP.nc'
        statistics_root: './databases/data/africa_ndvi_statistics.npz'
        train: [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        val:   [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        test:  [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        batch_size: 1
        tpb: 230
        root_ENSO: './databases/data/inino34_daily.dat'
        root_LC: './databases/data/africa_LC.tif'
    AfricaNDVIns:
        seed_idx: 0
        input_size: (150, 150)
        dense_input_size: 11719 
        root: './databases/data/africa_ndvi_noseasonality/'
        template: 'ndvi_noseasonality_TMSTMP.nc'
        statistics_root: './databases/data/africa_ndvi_noseasonality_statistics.npz'
        train: [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        val:   [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        test:  [2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        batch_size: 1
        tpb: 506
        root_ENSO: './databases/data/inino34_daily.dat'
        root_LC: './databases/data/africa_LC.tif'
    NDVI:
        seed_idx: 0
        input_size: (360, 720)
        dense_input_size: 60104 
        root: './databases/data/ndvi/'
        template: 'ndvi_TMSTMP.nc'
        statistics_root: './databases/data/ndvi_statistics.npz'
        train: [2007, 2008, 2009, 2010, 2011]
        val:   [2013, 2014, 2015, 2016, 2017]
        test:  [2013, 2014, 2015, 2016, 2017]
        batch_size: 1
        tpb: 150
        root_ENSO: './databases/data/inino34_daily.dat'
        root_LC: './databases/data/LC_hd_global_2012_full.tif'
data_loader: 
    device: 'cpu' # 'cpu', 'cuda'
    num_workers: 8
    pin_memory: true
optimizer:
    type: "Adam"
    lr: 0.001
    weight_decay: 0
    metrics: ["roc_auc"]
trainer:       
    epochs: 4000
    save_period: 1
    verbosity: 2
    monitor: "min val_loss"
    early_stop: 10
    tensorboard: true 
    codeDir: "./"
    save_dir: "./predictions"
    save_predictions: true
    my_dpi: 96
visualization:
    interpretation: false
