# Config file
name: "LatentGranger"
n_gpu: 0
arch:
    LatentGranger:
        encoder:
            out_features: (512, 256, 128)
        latent_dim: 5
        decoder:
            out_features: (128, 256, 512)
        beta: 0.01
        lag: 4
    resume: ""
    initial_weights: ''
data:
    Mnist: 
        input_size : (28,28)
        nsamples_train: 300
        nsamples_val: 300
        nsamples_test: 300
        tbp: 100
        batch_size: 1
        root: './databases/data/mnist'
    Toy:
        seed_idx: 0
        root: './databases/data/toy'
        input_size: (128,128)
        dense_input_size: 16384
        dimension: 1
        statistics_root: './databases/data/toy/data_py/statistics.npz'
        nsamples_train: 300
        nsamples_val: 300
        nsamples_test: 300
        batch_size: 1
        tpb: 300
    AfricaPrecip:
        seed_idx: 0
        input_size: (150, 150)
        dense_input_size: 11719 
        root: './databases/data/africa_precip/'
        years:  [1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999,  2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        nsamples_train: 600
        nsamples_val: 600
        nsamples_test: 200
        batch_size: 1
        tpb: 400
        root_ENSO: './databases/data/inino34_daily.dat'
        root_LC: './databases/data/africa_LC.tif'
    AfricaPrecipns:
        seed_idx: 0
        input_size: (150, 150)
        dense_input_size: 11719 
        root: './databases/data/africa_precip_ns/'
        years:  [2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
        nsamples_train: 400
        nsamples_val: 200
        nsamples_test: 200
        batch_size: 1
        tpb: 200
        root_ENSO: './databases/data/inino34_daily.dat'
        root_LC: './databases/data/africa_LC.tif'
    AfricaNDVI:
        seed_idx: 0
        input_size: (150, 150)
        dense_input_size: 11719 
        root: './databases/data/africa_ndvi/'
        template: 'ndvi_TMSTMP.nc'
        train: [2012, 2013, 2014, 2015, 2016]
        val:   [2007, 2008, 2009, 2010, 2011]
        test:  [2012, 2013, 2014, 2015, 2016]
        batch_size: 1
        tpb: 200
        root_ENSO: './databases/data/inino34_daily.dat'
        root_LC: './databases/data/africa_LC.tif'
    AfricaNDVIns:
        seed_idx: 0
        input_size: (150, 150)
        dense_input_size: 11719 
        root: './databases/data/africa_ndvi_norm/'
        template: 'ndvi_TMSTMP.nc'
        train: [2012, 2013, 2014, 2015, 2016]
        val:   [2007, 2008, 2009, 2010, 2011]
        test:  [2012, 2013, 2014, 2015, 2016]
        batch_size: 1
        tpb: 200
        root_ENSO: './databases/data/inino34_daily.dat'
        root_LC: './databases/data/africa_LC.tif'
data_loader: 
    device: 'cpu' # 'cpu', 'cuda'
    num_workers: 8
    pin_memory: true
optimizer:
    type: "Adam"
    lr: 0.0001
    weight_decay: 0
    metrics: ["roc_auc"]
trainer:       
    epochs: 4000
    save_period: 1
    verbosity: 2
    monitor: "min val_loss"
    early_stop: 10
    tensorboard: true 
    codeDir: "./"
    save_dir: "./predictions"
    save_predictions: true
    my_dpi: 96
visualization:
    interpretation: false
